apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    environment: prod
patches:
- path: balancereader.yaml
- path: contacts.yaml
- path: ledgerwriter.yaml
- path: loadgenerator.yaml
- path: transactionhistory.yaml
- path: userservice.yaml
- path: frontend.yaml
